version: '2'

services:
  artemis:
    image: vromero/activemq-artemis:2-alpine-latest
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    volumes:
      - ./artemisConfiguration:/var/lib/artemis/etc-override
    environment:
      ARTEMIS_USERNAME: weatherdata
      ARTEMIS_PASSWORD: thunderstorm
  eclipse-mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

